spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

  main:
    web-application-type: servlet

management:
  endpoints:
    web:
      exposure:
        include: "*"
