-- ─────────────────────────────────────────────────────────────────────────
-- Migración V1: Inicialización del esquema de Gresk
--
-- Esta es la primera migración. Flyway la ejecutará una sola vez y registrará
-- su checksum en la tabla `flyway_schema_history`.
--
-- Convención de nombres:
--   V{version}__{descripcion}.sql
--   - V1        → número de versión (entero, sin ceros a la izquierda)
--   - __        → doble guión bajo, separador obligatorio
--   - init      → descripción libre en snake_case
--   - .sql      → extensión obligatoria
--
-- IMPORTANTE: una vez que este fichero se ha ejecutado en cualquier entorno,
-- NO se puede modificar. Flyway guarda el checksum (hash del contenido) y
-- si detecta que el fichero cambió lanzará un error de "checksum mismatch"
-- para proteger la integridad del esquema. Cualquier cambio futuro se hace
-- en un nuevo fichero V2__....sql.
-- ─────────────────────────────────────────────────────────────────────────
